# [
#   { abbr: 'AK', full: 'Alaska',                conference: 'Pacific',  is_foreign: false, tz_offset: -9.hours.to_i,  dst: true  },
#   { abbr: 'AL', full: 'Alabama',               conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'AR', full: 'Arkansas',              conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'AZ', full: 'Arizona',               conference: 'Pacific',  is_foreign: false, tz_offset: -7.hours.to_i,  dst: false },
#   { abbr: 'CA', full: 'California',            conference: 'Pacific',  is_foreign: false, tz_offset: -8.hours.to_i,  dst: true  },
#   { abbr: 'CO', full: 'Colorado',              conference: 'Mountain', is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
#   { abbr: 'CT', full: 'Connecticut',           conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'DC', full: 'District of Columbia',  conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'DE', full: 'Delaware',              conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'FL', full: 'Florida',               conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'GA', full: 'Georgia',               conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'HI', full: 'Hawaii',                conference: 'Pacific',  is_foreign: false, tz_offset: -10.hours.to_i, dst: false },
#   { abbr: 'IA', full: 'Iowa',                  conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'ID', full: 'Idaho',                 conference: 'Mountain', is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
#   { abbr: 'IL', full: 'Illinois',              conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'IN', full: 'Indiana',               conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'KS', full: 'Kansas',                conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'KY', full: 'Kentucky',              conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'LA', full: 'Louisiana',             conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'MA', full: 'Massachusetts',         conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'MD', full: 'Maryland',              conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'ME', full: 'Maine',                 conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'MI', full: 'Michigan',              conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'MN', full: 'Minnesota',             conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'MO', full: 'Missouri',              conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'MS', full: 'Mississippi',           conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'MT', full: 'Montana',               conference: 'Mountain', is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
#   { abbr: 'NC', full: 'North Carolina',        conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'ND', full: 'North Dakota',          conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'NE', full: 'Nebraska',              conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'NH', full: 'New Hampshire',         conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'NJ', full: 'New Jersey',            conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'NM', full: 'New Mexico',            conference: 'Mountain', is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
#   { abbr: 'NV', full: 'Nevada',                conference: 'Pacific',  is_foreign: false, tz_offset: -8.hours.to_i,  dst: true  },
#   { abbr: 'NY', full: 'New York',              conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'OH', full: 'Ohio',                  conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'OK', full: 'Oklahoma',              conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'OR', full: 'Oregon',                conference: 'Pacific',  is_foreign: false, tz_offset: -8.hours.to_i,  dst: true  },
#   { abbr: 'PA', full: 'Pennsylvania',          conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'RI', full: 'Rhode Island',          conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'SC', full: 'South Carolina',        conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'SD', full: 'South Dakota',          conference: 'Central',  is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
#   { abbr: 'TN', full: 'Tennessee',             conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'TX', full: 'Texas',                 conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'UT', full: 'Utah',                  conference: 'Mountain', is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
#   { abbr: 'VA', full: 'Virginia',              conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'VT', full: 'Vermont',               conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'WA', full: 'Washington',            conference: 'Pacific',  is_foreign: false, tz_offset: -8.hours.to_i,  dst: true  },
#   { abbr: 'WI', full: 'Wisconsin',             conference: 'Central',  is_foreign: false, tz_offset: -6.hours.to_i,  dst: true  },
#   { abbr: 'WV', full: 'West Virginia',         conference: 'East',     is_foreign: false, tz_offset: -5.hours.to_i,  dst: true  },
#   { abbr: 'WY', full: 'Wyoming',               conference: 'Mountain', is_foreign: false, tz_offset: -7.hours.to_i,  dst: true  },
# ].each {|state| State.create(state) unless State.find_by(abbr: state[:abbr]) }
