# sr_only_teams = {
#   "AL FB" => 2020,
#   "DE FB" => 2020,
#   "FL FB" => 2020,
#   "IL BBB" => 2020,
#   "IL FB" => 2020,
#   "IL GBB" => 2020,
#   "IL VB" => 2020,
#   "LA FB" => 2020,
#   "MI FB" => 2020,
#   "NC FB" => 2020,
#   "OH FB" => 2020,
#   "PA FB" => 2020,
#   "VA FB" => 2020,
#   "WI FB" => 2020,
#   "WV FB" => 2020
# }
#
# ok_invite = {
#   'AK' =>  true,
#   'AL' =>  true,
#   'AR' =>  true,
#   'AZ' =>  true,
#   'CA' =>  true,
#   'CO' =>  true,
#   'CT' =>  true,
#   'DC' =>  true,
#   'DE' =>  true,
#   'FL' =>  true,
#   'GA' =>  true,
#   'HI' =>  false,
#   'IA' =>  true,
#   'ID' =>  true,
#   'IL' =>  true,
#   'IN' =>  true,
#   'KS' =>  true,
#   'KY' =>  true,
#   'LA' =>  true,
#   'MA' =>  false,
#   'MD' =>  false,
#   'ME' =>  false,
#   'MI' =>  true,
#   'MN' =>  true,
#   'MO' =>  true,
#   'MS' =>  true,
#   'MT' =>  true,
#   'NC' =>  true,
#   'ND' =>  true,
#   'NE' =>  true,
#   'NH' =>  true,
#   'NJ' =>  true,
#   'NM' =>  true,
#   'NV' =>  true,
#   'NY' =>  true,
#   'OH' =>  true,
#   'OK' =>  true,
#   'OR' =>  true,
#   'PA' =>  true,
#   'RI' =>  true,
#   'SC' =>  true,
#   'SD' =>  true,
#   'TN' =>  false,
#   'TX' =>  true,
#   'UT' =>  true,
#   'VA' =>  true,
#   'VT' =>  false,
#   'WA' =>  true,
#   'WI' =>  true,
#   'WV' =>  true,
#   'WY' =>  true,
# }
#
# no_cert = {
#   "MO TF" => true,
#   "WI VB" => true,
#   "AL FB" => true,
#   "WV FB" => true,
#   "WI XC" => true,
#   "FL XC" => true,
#   "MO XC" => true,
#   "OH XC" => true,
#   "PA XC" => true,
#   "MO VB" => true,
#   "WI TF" => true,
#   "NC FB" => true,
#   "OH FB" => true,
#   "FL GF" => true,
#   "PA FB" => true,
#   "VA FB" => true,
#   "WI FB" => true,
#   "MO GF" => true,
#   "OH GF" => true,
#   "PA GF" => true,
#   "WI GF" => true,
#   "DE FB" => true,
#   "FL FB" => true,
#   "IL FB" => true,
#   "LA FB" => true,
#   "MI FB" => true,
#   "MO FB" => true,
#   "FL VB" => true,
#   "IL VB" => true,
#   "OH VB" => true,
#   "PA VB" => true,
#   "FL TF" => true,
#   "OH TF" => true,
#   "PA TF" => true,
#   "WI GBB" => true,
#   "FL GBB" => true,
#   "IL GBB" => true,
#   "MO GBB" => true,
#   "OH GBB" => true,
#   "PA GBB" => true,
#   "FL BBB" => true,
#   "IL BBB" => true,
#   "MO BBB" => true,
#   "OH BBB" => true,
#   "PA BBB" => true,
#   "WI BBB" => true
# }
#
# State.all.each do |state|
#   Sport.where.not(id: Invite::Rule.where(state: state).select(:sport_id)).each do |sport|
#     Invite::Rule.create(
#       state: state,
#       sport: sport,
#       invitable: !!ok_invite[state.abbr],
#       certifiable: !no_cert["#{state.abbr} #{sport.abbr_gender}"],
#       grad_year: sr_only_teams["#{state.abbr} #{sport.abbr_gender}"] || 2022
#     )
#   end
# end
